# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-spliz-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.6
  - pandas=1.3.1
  - tqdm=4.62.0
  - numpy=1.21.1
  - pyarrow=5.0.0
  - pysam=0.16.0.1
  - r-base=4.1.1  
  - r-data.table=1.14.0 
  - r-logger=0.2.1
  - r-rfast=2.0.3 
  - scipy=1.7.1
  - statsmodels=0.12.2
  - nextflow=21.04.0
  - bedtools
